-- Inserts do Banco

USE myreceitas_db;

INSERT INTO recipes (name, ingredients, description, preparation_time, category, price, is_public) VALUES
('Bolo de Chocolate', 'farinha de trigo, açúcar, cacau em pó, ovos, leite, fermento, óleo', 'Misture os ingredientes secos, adicione os líquidos, bata até homogeneizar. Asse em forma untada por 40 minutos.', 40, 'sobremesa', 15.00, TRUE),
('Salada Caesar', 'alface romana, peito de frango, parmesão, croutons, molho caesar', 'Lave e rasgue a alface. Grelhe o frango e corte em tiras. Misture todos os ingredientes e finalize com o molho.', 20, 'salada', 25.00, TRUE),
('Macarrão à Carbonara', 'macarrão spaghetti, ovos, queijo pecorino, pancetta, pimenta preta', 'Cozinhe o macarrão al dente. Enquanto isso, frite a pancetta. Bata os ovos com o queijo. Misture tudo com o macarrão quente.', 25, 'massa', 30.00, TRUE),
('Frango Grelhado com Legumes', 'peito de frango, brócolis, cenoura, abobrinha, azeite, alho, limão', 'Tempere o frango com alho, limão e azeite. Grelhe em fogo médio. Cozinhe os legumes no vapor e sirva junto.', 35, 'prato principal', 28.00, TRUE),
('Sopa de Cebola', 'cebola, caldo de carne, pão, queijo gruyère', 'Refogue as cebolas até caramelizar. Adicione o caldo e cozinhe. Sirva com fatias de pão e queijo gratinado.', 30, 'sopa', 18.00, TRUE),
('Torta de Limão', 'bolacha maria, manteiga, leite condensado, suco de limão, creme de leite', 'Faça a base com as bolachas trituradas e manteiga. Recheie com a mistura de leite condensado, suco e creme. Leve à geladeira.', 60, 'sobremesa', 22.00, TRUE),
('Hambúrguer Artesanal', 'carne moída, cebola, alho, pão de hambúrguer, alface, tomate, queijo cheddar', 'Tempere a carne com cebola e alho, modele os hambúrgueres e grelhe. Monte com os acompanhamentos.', 20, 'lanche', 20.00, TRUE),
('Risoto de Cogumelos', 'arroz arbóreo, cogumelos frescos, caldo de legumes, vinho branco, cebola, parmesão', 'Refogue a cebola, adicione o arroz, vinho e caldo aos poucos. Incorpore os cogumelos e finalize com parmesão.', 45, 'prato principal', 35.00, TRUE),
('Smoothie de Frutas Vermelhas', 'morango, framboesa, amora, iogurte, mel', 'Bata todos os ingredientes no liquidificador até ficar homogêneo.', 5, 'bebida', 12.00, TRUE),
('Espaguete ao Pesto', 'espaguete, manjericão, pinhões, queijo parmesão, azeite, alho', 'Bata o manjericão, pinhões, parmesão, alho e azeite no processador. Cozinhe o macarrão e misture.', 20, 'massa', 26.00, TRUE),
('Peixe Assado com Ervas', 'filé de peixe branco, alecrim, tomilho, limão, azeite, alho', 'Tempere o peixe com ervas, limão e azeite. Asse em forno médio por 25 minutos.', 30, 'peixe', 32.00, TRUE),
('Pão de Queijo', 'polvilho azedo, leite, óleo, ovos, queijo minas ralado', 'Misture todos os ingredientes, molde bolinhas e asse até dourar.', 30, 'lanche', 8.00, TRUE),
('Sopa de Legumes', 'cenoura, batata, abobrinha, alho-poró, caldo de legumes', 'Cozinhe todos os legumes no caldo até ficarem macios. Bata ou sirva em pedaços.', 40, 'sopa', 14.00, TRUE),
('Brownie de Chocolate', 'chocolate amargo, manteiga, açúcar, ovos, farinha, nozes', 'Derreta o chocolate com a manteiga, misture os demais ingredientes e asse por 25 minutos.', 45, 'sobremesa', 18.00, TRUE),
('Camarão ao Alho e Óleo', 'camarão, alho, azeite, limão, salsinha', 'Refogue o alho no azeite, adicione os camarões e cozinhe até ficarem rosados. Finalize com limão e salsinha.', 15, 'prato principal', 40.00, TRUE),
('Salada de Quinoa', 'quinoa, pepino, tomate, cebola roxa, hortelã, limão, azeite', 'Cozinhe a quinoa, misture com os vegetais picados e tempere com limão e azeite.', 25, 'salada', 22.00, TRUE),
('Panqueca Americana', 'farinha, açúcar, ovos, leite, fermento, manteiga', 'Misture os ingredientes, cozinhe em frigideira untada até borbulhar, vire e doure.', 15, 'lanche', 10.00, TRUE),
('Costela Barbecue', 'costela suína, molho barbecue, alho, cebola, sal, pimenta', 'Tempere a costela, asse em forno baixo por 2 horas, pincele com molho barbecue nos últimos 15 minutos.', 120, 'carne', 45.00, TRUE),
('Torta de Maçã', 'massa folhada, maçã, açúcar, canela, suco de limão', 'Corte as maçãs, misture com açúcar e canela. Forre a forma com a massa, coloque o recheio e cubra com tiras de massa.', 50, 'sobremesa', 20.00, TRUE),
('Cuscuz Marroquino', 'cuscuz, legumes variados, grão-de-bico, especiarias', 'Hidrate o cuscuz com caldo quente. Refogue os legumes e misture com o cuscuz e grão-de-bico.', 30, 'prato principal', 27.00, TRUE),
('Mousse de Maracujá', 'suco de maracujá, leite condensado, creme de leite, gelatina sem sabor', 'Bata todos os ingredientes e leve à geladeira por 2 horas.', 20, 'sobremesa', 16.00, TRUE),
('Wrap de Frango', 'tortilha, frango desfiado, alface, tomate, molho iogurte', 'Aqueça a tortilha, recheie com frango e os demais ingredientes, enrole e sirva.', 10, 'lanche', 15.00, TRUE),
('Bacalhau à Brás', 'bacalhau desfiado, batata palha, cebola, ovos, azeitonas', 'Refogue a cebola, adicione o bacalhau e as batatas. Misture os ovos mexidos e finalize com azeitonas.', 35, 'peixe', 38.00, TRUE),
('Salada de Frutas', 'morango, banana, maçã, uva, laranja, mel', 'Corte as frutas em pedaços, misture e sirva com mel.', 10, 'sobremesa', 8.00, TRUE),
('Macarrão com Molho de Tomate', 'macarrão, tomate pelado, cebola, alho, manjericão, azeite', 'Refogue a cebola e o alho, adicione os tomates e cozinhe. Misture com o macarrão cozido.', 25, 'massa', 18.00, TRUE),
('Kafta Grega', 'carne moída, cebola, salsinha, hortelã, especiarias', 'Misture todos os ingredientes, modele em formato de charuto e grelhe.', 30, 'carne', 24.00, TRUE),
('Cheesecake de Frutas Vermelhas', 'biscoito, manteiga, cream cheese, açúcar, ovos, geleia de frutas', 'Faça a base com biscoito e manteiga, bata o cream cheese com açúcar e ovos, asse em banho-maria. Cubra com geleia.', 70, 'sobremesa', 30.00, TRUE),
('Omelete de Espinafre', 'ovos, espinafre, queijo feta, cebola, sal', 'Bata os ovos, refogue o espinafre e a cebola, misture e cozinhe até firmar.', 15, 'prato principal', 14.00, TRUE),
('Sopa de Tomate com Manjericão', 'tomate, cebola, alho, caldo de legumes, manjericão, creme de leite', 'Refogue a cebola e alho, adicione os tomates e caldo. Cozinhe, bata, finalize com manjericão e creme.', 35, 'sopa', 16.00, TRUE),
('Bolinho de Arroz', 'arroz cozido, farinha, ovos, queijo, salsinha', 'Misture todos os ingredientes, modele bolinhas e frite.', 20, 'lanche', 6.00, TRUE),
('Lasanha à Bolonhesa', 'massa de lasanha, carne moída, molho de tomate, bechamel, queijo parmesão', 'Monte camadas de massa, molho bolonhesa, bechamel e parmesão. Asse por 30 minutos.', 60, 'massa', 35.00, TRUE),
('Pudim de Leite Condensado', 'leite condensado, leite, ovos, caramelo', 'Bata todos os ingredientes, despeje em forma com caramelo e cozinhe em banho-maria por 1 hora.', 70, 'sobremesa', 12.00, TRUE),
('Salmão Grelhado', 'salmão, azeite, limão, alho, endro', 'Tempere o salmão e grelhe por 5 minutos de cada lado.', 15, 'peixe', 35.00, TRUE),
('Cuscuz Paulista', 'farinha de milho, caldo de galinha, cebola, tomate, salsinha, ovo', 'Refogue a cebola e tomate, adicione o caldo e a farinha, mexa até engrossar. Coloque em forma e decore com ovo.', 30, 'prato principal', 20.00, TRUE),
('Tapioca com Coco', 'goma de tapioca, coco ralado, leite condensado', 'Hidrate a goma, peneire e cozinhe em frigideira. Recheie com coco e leite condensado.', 10, 'lanche', 7.00, TRUE),
('Ragu de Carne', 'carne bovina, vinho tinto, tomate, cebola, cenoura, alecrim', 'Cozinhe a carne em panela de pressão com os vegetais e vinho, desfie e sirva.', 90, 'carne', 42.00, TRUE),
('Quiche de Alho-poró', 'massa quebrada, alho-poró, ovos, creme de leite, queijo gruyère', 'Faça a base da quiche, recheie com alho-poró refogado, mistura de ovos e creme, cubra com queijo e asse.', 50, 'prato principal', 28.00, TRUE),
('Sopa de Abóbora', 'abóbora, cebola, alho, gengibre, caldo de galinha, creme de leite', 'Cozinhe a abóbora com os temperos, bata, acrescente o creme.', 30, 'sopa', 15.00, TRUE),
('Beijinho de Coco', 'leite condensado, coco ralado, manteiga, açúcar', 'Cozinhe todos os ingredientes até desgrudar da panela, modele bolinhas e passe no coco.', 25, 'sobremesa', 5.00, TRUE),
('Yakisoba', 'macarrão yakisoba, frango, legumes (brócolis, cenoura, pimentão), molho shoyu', 'Refogue o frango e legumes, adicione o macarrão cozido e o molho shoyu, misture bem.', 30, 'prato principal', 26.00, TRUE),
('Pão de Alho', 'pão francês, manteiga, alho, salsinha, queijo', 'Misture a manteiga com alho e salsinha, passe no pão, cubra com queijo e leve ao forno.', 15, 'lanche', 10.00, TRUE),
('Carpaccio de Carne', 'filé mignon, alcaparras, parmesão, rúcula, azeite, limão', 'Corte a carne em fatias finas, disponha com rúcula, alcaparras, parmesão e regue com azeite e limão.', 15, 'entrada', 32.00, TRUE),
('Bolo de Cenoura com Cobertura de Chocolate', 'cenoura, farinha, açúcar, ovos, óleo, fermento, chocolate', 'Bata a cenoura com os líquidos, misture os secos, asse. Cobertura: derreta chocolate com creme de leite.', 50, 'sobremesa', 18.00, TRUE),
('Feijoada Light', 'feijão preto, carne seca, linguiça, bacon, cebola, alho, louro', 'Cozinhe o feijão com as carnes dessalgadas e temperos, sirva com arroz e couve.', 120, 'prato principal', 30.00, TRUE),
('Suco Detox', 'couve, gengibre, limão, maçã, água de coco', 'Bata todos os ingredientes no liquidificador e sirva gelado.', 5, 'bebida', 9.00, TRUE),
('Nhoque de Batata', 'batata, farinha de trigo, ovo, sal, manteiga, molho de tomate', 'Cozinhe as batatas, amasse, misture com farinha e ovo. Modele os nhoques e cozinhe em água fervente. Sirva com molho.', 60, 'massa', 24.00, TRUE),
('Bruschetta', 'pão italiano, tomate, manjericão, alho, azeite, sal', 'Torre o pão, esfregue alho, cubra com tomate picado e manjericão, regue com azeite.', 10, 'entrada', 12.00, TRUE),
('Arroz de Forno', 'arroz cozido, frango desfiado, milho, ervilha, queijo, creme de leite', 'Misture todos os ingredientes, coloque em refratário, cubra com queijo e gratine.', 40, 'prato principal', 22.00, TRUE),
('Gelatina Colorida', 'gelatina de sabores variados, leite condensado', 'Prepare gelatinas separadamente, deixe firmar, corte em cubos e misture com leite condensado.', 30, 'sobremesa', 6.00, TRUE),
('Pastel de Forno', 'massa de pastel, carne moída refogada, azeitona, queijo', 'Recheie os pastéis com a carne e azeitona, feche, pincele com gema e asse.', 25, 'lanche', 12.00, TRUE);
