-- Inserts do Banco

USE myreceitas_db;
	
    INSERT INTO users (name, email, password, phone, address, photo) VALUES
	("Matheus Yhudi Busemeier Fermiano", "matheus_fermiano@estudante.sesisenai.org.br", "$2y$12$DY394qbskCuXUciF7FtZFulRMLdEdWOqUzDNYhGI2.fpTypVpRbMy", "47 1234-5678", "rua dos bobos, Nº0", "default_user.png"),
    ("Pedro HAH", "pedro_habizenreuter@estudante.sesisenai.org.br", "$2y$12$DY394qbskCuXUciF7FtZFulRMLdEdWOqUzDNYhGI2.fpTypVpRbMy", "47 4321-5678", "rua dos bobos, Nº10", "default_user.png");

-- =====================================================
-- INSERTS PARA A TABELA `users`
-- =====================================================

INSERT INTO users (name, email, password, phone, address, photo, is_active, login_attempts, last_login, reset_token, reset_token_expiry, deleted_at) VALUES
('Ana Clara Oliveira', 'ana.oliveira@email.com', '$2y$12$DY394qbskCuXUciF7FtZFulRMLdEdWOqUzDNYhGI2.fpTypVpRbMy', '(11) 91234-5678', 'Rua das Flores, 123, São Paulo, SP', 'default_user.png', TRUE, 0, NULL, NULL, NULL, NULL),
('Bruno Mendes', 'bruno.mendes@email.com', '$2y$12$DY394qbskCuXUciF7FtZFulRMLdEdWOqUzDNYhGI2.fpTypVpRbMy', '(21) 99876-5432', 'Av. Atlântica, 456, Rio de Janeiro, RJ', 'default_user.png', TRUE, 0, NULL, NULL, NULL, NULL),
('Carla Souza', 'carla.souza@email.com', '$2y$12$DY394qbskCuXUciF7FtZFulRMLdEdWOqUzDNYhGI2.fpTypVpRbMy', '(31) 98888-7777', 'Rua da Liberdade, 789, Belo Horizonte, MG', 'default_user.png', TRUE, 0, NULL, NULL, NULL, NULL),
('Daniel Ferreira', 'daniel.ferreira@email.com', '$2y$12$DY394qbskCuXUciF7FtZFulRMLdEdWOqUzDNYhGI2.fpTypVpRbMy', '(41) 97777-6666', 'Rua XV de Novembro, 1010, Curitiba, PR', 'default_user.png', TRUE, 0, NULL, NULL, NULL, NULL),
('Elena Rocha', 'elena.rocha@email.com', '$2y$12$DY394qbskCuXUciF7FtZFulRMLdEdWOqUzDNYhGI2.fpTypVpRbMy', '(51) 96666-5555', 'Rua dos Andradas, 2020, Porto Alegre, RS', 'default_user.png', TRUE, 0, NULL, NULL, NULL, NULL),
('Fernando Lima', 'fernando.lima@email.com', '$2y$12$DY394qbskCuXUciF7FtZFulRMLdEdWOqUzDNYhGI2.fpTypVpRbMy', '(61) 95555-4444', 'Setor Comercial Sul, 3030, Brasília, DF', 'default_user.png', TRUE, 0, NULL, NULL, NULL, NULL),
('Gabriela Martins', 'gabriela.martins@email.com', '$2y$12$DY394qbskCuXUciF7FtZFulRMLdEdWOqUzDNYhGI2.fpTypVpRbMy', '(71) 94444-3333', 'Av. Paralela, 4040, Salvador, BA', 'default_user.png', TRUE, 0, NULL, NULL, NULL, NULL),
('Henrique Nunes', 'henrique.nunes@email.com', '$2y$12$DY394qbskCuXUciF7FtZFulRMLdEdWOqUzDNYhGI2.fpTypVpRbMy', '(81) 93333-2222', 'Rua do Bom Jesus, 5050, Recife, PE', 'default_user.png', TRUE, 0, NULL, NULL, NULL, NULL),
('Isabela Pereira', 'isabela.pereira@email.com', '$2y$12$DY394qbskCuXUciF7FtZFulRMLdEdWOqUzDNYhGI2.fpTypVpRbMy', '(91) 92222-1111', 'Av. Presidente Vargas, 6060, Belém, PA', 'default_user.png', TRUE, 0, NULL, NULL, NULL, NULL),
('João Victor Santos', 'joao.santos@email.com', '$2y$12$DY394qbskCuXUciF7FtZFulRMLdEdWOqUzDNYhGI2.fpTypVpRbMy', '(11) 91111-0000', 'Rua Augusta, 7070, São Paulo, SP', 'default_user.png', TRUE, 0, NULL, NULL, NULL, NULL);

-- =====================================================
-- INSERTS PARA A TABELA `chef`
-- =====================================================

INSERT INTO chef (name, email, password, description, phone, address, professional_experience, services_offered, region_operation, photo, is_active, login_attempts, last_login, reset_token, reset_token_expiry, deleted_at) VALUES
('Chef Ricardo Alves', 'ricardo.alves@chef.com', '$2y$12$DY394qbskCuXUciF7FtZFulRMLdEdWOqUzDNYhGI2.fpTypVpRbMy', 'Especialista em culinária italiana com toque contemporâneo.', '(11) 91234-0001', 'Rua dos Cozinheiros, 100, São Paulo, SP', '10 anos como chef executivo em restaurantes italianos. Experiência em eventos e catering.', 'Jantares privados, Aulas de culinária, Cardápios personalizados', 'Grande São Paulo', 'default_chef.png', TRUE, 0, NULL, NULL, NULL, NULL),
('Chef Beatriz Castro', 'beatriz.castro@chef.com', '$2y$12$DY394qbskCuXUciF7FtZFulRMLdEdWOqUzDNYhGI2.fpTypVpRbMy', 'Cozinha francesa e confeitaria artesanal.', '(21) 99876-0002', 'Av. das Gastronomias, 200, Rio de Janeiro, RJ', 'Formada em Le Cordon Bleu, atuou em padarias francesas e restaurantes finos.', 'Confeitaria, Buffet de eventos, Jantares temáticos', 'Zona Sul do Rio', 'default_chef.png', TRUE, 0, NULL, NULL, NULL, NULL),
('Chef Carlos Eduardo', 'carlos.eduardo@chef.com', '$2y$12$DY394qbskCuXUciF7FtZFulRMLdEdWOqUzDNYhGI2.fpTypVpRbMy', 'Cozinha brasileira contemporânea com ingredientes regionais.', '(31) 98888-0003', 'Rua dos Sabores, 300, Belo Horizonte, MG', 'Chef de cozinha em restaurantes mineiros, participou de festivais gastronômicos.', 'Comida típica mineira, Eventos corporativos, Consultoria', 'Região Metropolitana de BH', 'default_chef.png', TRUE, 0, NULL, NULL, NULL, NULL),
('Chef Daniela Mello', 'daniela.mello@chef.com', '$2y$12$DY394qbskCuXUciF7FtZFulRMLdEdWOqUzDNYhGI2.fpTypVpRbMy', 'Especialista em culinária vegana e saudável.', '(41) 97777-0004', 'Rua Verde, 400, Curitiba, PR', 'Atua há 5 anos com alimentação plant-based, já publicou um livro de receitas.', 'Jantares veganos, Oficinas de alimentação saudável, Cardápios especiais', 'Curitiba e região', 'default_chef.png', TRUE, 0, NULL, NULL, NULL, NULL),
('Chef Eduardo Santos', 'eduardo.santos@chef.com', '$2y$12$DY394qbskCuXUciF7FtZFulRMLdEdWOqUzDNYhGI2.fpTypVpRbMy', 'Cozinha portuguesa e frutos do mar.', '(51) 96666-0005', 'Rua do Mar, 500, Porto Alegre, RS', 'Trabalhou em restaurantes portugueses em Lisboa e no Brasil.', 'Frutos do mar, Petiscos portugueses, Eventos temáticos', 'Litoral gaúcho', 'default_chef.png', TRUE, 0, NULL, NULL, NULL, NULL),
('Chef Fernanda Lima', 'fernanda.lima@chef.com', '$2y$12$DY394qbskCuXUciF7FtZFulRMLdEdWOqUzDNYhGI2.fpTypVpRbMy', 'Cozinha asiática fusion.', '(61) 95555-0006', 'Setor Gastronômico, 600, Brasília, DF', 'Estudou na Tailândia e Japão, com experiência em restaurantes orientais.', 'Sushis, culinária tailandesa, Jantares temáticos', 'Brasília e entorno', 'default_chef.png', TRUE, 0, NULL, NULL, NULL, NULL),
('Chef Gustavo Rocha', 'gustavo.rocha@chef.com', '$2y$12$DY394qbskCuXUciF7FtZFulRMLdEdWOqUzDNYhGI2.fpTypVpRbMy', 'Cozinha regional nordestina.', '(71) 94444-0007', 'Av. da Praia, 700, Salvador, BA', 'Chef de cozinha em restaurantes típicos baianos, especialista em moquecas.', 'Comida baiana, Eventos e festas, Aulas de culinária', 'Salvador e litoral norte', 'default_chef.png', TRUE, 0, NULL, NULL, NULL, NULL),
('Chef Helena Martins', 'helena.martins@chef.com', '$2y$12$DY394qbskCuXUciF7FtZFulRMLdEdWOqUzDNYhGI2.fpTypVpRbMy', 'Cozinha italiana e mediterrânea.', '(81) 93333-0008', 'Rua da Boa Vista, 800, Recife, PE', 'Atuou em restaurantes italianos na Itália e em Pernambuco.', 'Massas artesanais, Risotos, Jantares românticos', 'Recife e litoral sul', 'default_chef.png', TRUE, 0, NULL, NULL, NULL, NULL),
('Chef Igor Nogueira', 'igor.nogueira@chef.com', '$2y$12$DY394qbskCuXUciF7FtZFulRMLdEdWOqUzDNYhGI2.fpTypVpRbMy', 'Cozinha molecular e gastronomia de vanguarda.', '(91) 92222-0009', 'Av. das Estrelas, 900, Belém, PA', 'Inovador na cozinha amazônica, participou de competições internacionais.', 'Experiências gastronômicas, Degustações, Eventos exclusivos', 'Belém e região amazônica', 'default_chef.png', TRUE, 0, NULL, NULL, NULL, NULL),
('Chef Juliana Almeida', 'juliana.almeida@chef.com', '$2y$12$DY394qbskCuXUciF7FtZFulRMLdEdWOqUzDNYhGI2.fpTypVpRbMy', 'Cozinha contemporânea com influência árabe.', '(11) 91111-0010', 'Rua das Delícias, 1000, São Paulo, SP', 'Especialista em culinária libanesa e síria, com passagem por restaurantes no Líbano.', 'Comida árabe, Buffet, Eventos empresariais', 'Grande São Paulo', 'default_chef.png', TRUE, 0, NULL, NULL, NULL, NULL);

-- =====================================================
-- INSERTS PARA A TABELA `restaurants`
-- =====================================================

INSERT INTO restaurants (name, email, password, phone, address, location_map_link, description, photo, opening_hours, services_offered, menu_description, is_active, deleted_at) VALUES
('La Trattoria', 'contato@latrattoria.com', '$2y$12$DY394qbskCuXUciF7FtZFulRMLdEdWOqUzDNYhGI2.fpTypVpRbMy', '(11) 1234-5678', 'Rua Italiana, 150, São Paulo, SP', 'https://maps.google.com/?q=Rua+Italiana,150,SP', 'Restaurante italiano com ambiente aconchegante e massas caseiras.', 'default_restaurant.png', '12:00-15:00, 19:00-23:00', 'Delivery, Reservas, Estacionamento', 'Massas frescas, Risotos, Pizzas artesanais.', TRUE, NULL),
('Sabor & Arte', 'saborarte@email.com', '$2y$12$DY394qbskCuXUciF7FtZFulRMLdEdWOqUzDNYhGI2.fpTypVpRbMy', '(21) 4321-8765', 'Av. das Artes, 250, Rio de Janeiro, RJ', 'https://maps.google.com/?q=Av.+das+Artes,250,RJ', 'Culinária contemporânea com toque artístico em cada prato.', 'default_restaurant.png', '11:00-16:00, 18:00-00:00', 'Buffet, Eventos, Cozinha aberta', 'Pratos executivos, Saladas, Carnes grelhadas.', TRUE, NULL),
('Mineirão Gourmet', 'mineirao@email.com', '$2y$12$DY394qbskCuXUciF7FtZFulRMLdEdWOqUzDNYhGI2.fpTypVpRbMy', '(31) 8765-4321', 'Rua das Minas, 350, Belo Horizonte, MG', 'https://maps.google.com/?q=Rua+das+Minas,350,BH', 'Tradicional comida mineira com ingredientes frescos da região.', 'default_restaurant.png', '11:30-15:30, 18:30-22:30', 'Delivery, Self-service, Estacionamento', 'Frango com quiabo, Feijão tropeiro, Doces caseiros.', TRUE, NULL),
('Maré Alta', 'marealta@email.com', '$2y$12$DY394qbskCuXUciF7FtZFulRMLdEdWOqUzDNYhGI2.fpTypVpRbMy', '(41) 5678-1234', 'Av. do Oceano, 450, Curitiba, PR', 'https://maps.google.com/?q=Av.+do+Oceano,450,Curitiba', 'Especializado em frutos do mar e peixes frescos.', 'default_restaurant.png', '12:00-16:00, 19:00-00:00', 'Delivery, Reservas, Acessibilidade', 'Moquecas, Camarões, Peixes grelhados.', TRUE, NULL),
('Verde Vivo', 'verdevivo@email.com', '$2y$12$DY394qbskCuXUciF7FtZFulRMLdEdWOqUzDNYhGI2.fpTypVpRbMy', '(51) 9876-5432', 'Rua dos Jardins, 550, Porto Alegre, RS', 'https://maps.google.com/?q=Rua+dos+Jardins,550,Porto+Alegre', 'Restaurante vegano e saudável, com opções criativas.', 'default_restaurant.png', '10:00-21:00', 'Delivery, Self-service, Retirada', 'Saladas, Hambúrgueres vegetais, Sucos naturais.', TRUE, NULL),
('Sushi House', 'sushihouse@email.com', '$2y$12$DY394qbskCuXUciF7FtZFulRMLdEdWOqUzDNYhGI2.fpTypVpRbMy', '(61) 2345-6789', 'Setor Asiático, 650, Brasília, DF', 'https://maps.google.com/?q=Setor+Asiático,650,DF', 'Autêntica culinária japonesa com sushis e sashimis de primeira.', 'default_restaurant.png', '12:00-15:00, 19:00-23:00', 'Delivery, Reservas, Rodízio', 'Sushis, Temakis, Combinados.', TRUE, NULL),
('Bahia Tropicana', 'bahiatropic@email.com', '$2y$12$DY394qbskCuXUciF7FtZFulRMLdEdWOqUzDNYhGI2.fpTypVpRbMy', '(71) 3456-7890', 'Av. da Praia, 750, Salvador, BA', 'https://maps.google.com/?q=Av.+da+Praia,750,Salvador', 'Cozinha baiana típica com acarajé, vatapá e moqueca.', 'default_restaurant.png', '11:00-23:00', 'Delivery, Eventos, Cardápio infantil', 'Comida baiana, Frutos do mar, Doces regionais.', TRUE, NULL),
('Sabor do Sertão', 'saborsertao@email.com', '$2y$12$DY394qbskCuXUciF7FtZFulRMLdEdWOqUzDNYhGI2.fpTypVpRbMy', '(81) 4567-8901', 'Rua do Sertão, 850, Recife, PE', 'https://maps.google.com/?q=Rua+do+Sertão,850,Recife', 'Comida nordestina com influência do sertão e do litoral.', 'default_restaurant.png', '11:30-16:00, 18:00-22:00', 'Buffet, Estacionamento, Ar-condicionado', 'Baião de dois, Carne de sol, Queijo coalho.', TRUE, NULL),
('Amazônia Grill', 'amazoniagrill@email.com', '$2y$12$DY394qbskCuXUciF7FtZFulRMLdEdWOqUzDNYhGI2.fpTypVpRbMy', '(91) 5678-9012', 'Av. da Floresta, 950, Belém, PA', 'https://maps.google.com/?q=Av.+da+Floresta,950,Belém', 'Churrascaria com carnes nobres e pratos típicos amazônicos.', 'default_restaurant.png', '12:00-16:00, 19:00-00:00', 'Delivery, Reservas, Self-service', 'Carnes variadas, Peixes regionais, Frutas típicas.', TRUE, NULL),
('Forno & Fogão', 'fornofogao@email.com', '$2y$12$DY394qbskCuXUciF7FtZFulRMLdEdWOqUzDNYhGI2.fpTypVpRbMy', '(11) 6789-0123', 'Rua das Padarias, 1050, São Paulo, SP', 'https://maps.google.com/?q=Rua+das+Padarias,1050,SP', 'Padaria e restaurante com pães artesanais e pratos caseiros.', 'default_restaurant.png', '06:00-22:00', 'Delivery, Retirada, Wi-Fi', 'Pães, Bolos, Salgados, Pratos executivos.', TRUE, NULL);